spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/nbcam?rewriteBatchedStatements=true
    username: root
    password: 12345678

  data:
    redis:
      host: localhost
      port: 6379

  jpa:
    hibernate:
      ddl-auto: update

jwt:
  secret:
    key: nlangjiabfiubasdhuabsjdbaksdnbiqwnjinjidasdasdffagwfgafgds

logging:
  level:
    org.springframework.security: debug

aws:
  s3:
    bucket-name: nbcam-test